import { ArrowLeft, Box, Check, CheckCircle2, ChevronRight, CircleAlert, PackageCheck, Plus, Printer, RefreshCw, RotateCcw, Truck, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { hasWarehousePermission, useAuth } from "../features/auth/AuthContext";
import { packageCarrierName, shippingPrintJobFor } from "../features/shipping/shipmentPresentation";
import { ApiError, getErrorMessage, shipmentApi, warehouseAdminApi, type PrintJob, type ReprintReason } from "../lib/api";
import type { BulkHandoffResult, GeliverLivePackage, ShipmentListItem, ShipmentV1 } from "../types/warehouse";

type Draft = { template: string; length: string; width: string; height: string; weight: string; contents: Record<string, string> };
type QueueItem = ShipmentListItem & { detail?: ShipmentV1 };
type Notice = { kind: "error" | "success" | "info"; message: string; code?: string };
type Recipient = NonNullable<ShipmentV1["recipient"]>;
const boxes = [{ name: "Küçük", size: [30,20,20] }, { name: "Orta", size: [40,30,25] }, { name: "Büyük", size: [50,40,30] }, { name: "Uzun", size: [100,30,30] }] as const;
const key = (): string => crypto.randomUUID();
const statusText: Record<string,string> = { PREPARING:"PAKETLENİYOR", CARRIER_SELECTED:"TEKLİF SEÇİLDİ", BOOKED:"ETİKET HAZIRLANIYOR", LABEL_READY:"SEVKE HAZIR", DISPATCHED:"SEVK EDİLDİ", EXCEPTION:"İNCELENMELİ" };
const preservedActionLabels = ["İptal et", "Fiziksel teslimi doğrula"] as const;
const fail = (error: unknown): Notice => ({ kind:"error", message:getErrorMessage(error), code:error instanceof ApiError ? error.code : undefined });
const packageName = (shipment: ShipmentV1, pack: ShipmentV1["packages"][number]) => `${shipment.orderNumber} · Paket ${pack.packageNumber} · ${pack.id.slice(0,8)}`;
const price = (amount?: string | null, currency?: string | null) => {
  const numeric = Number(amount); if (!Number.isFinite(numeric)) return `${amount || "—"} ${currency || ""}`.trim();
  try { return new Intl.NumberFormat("tr-TR", { style:"currency", currency:currency || "TRY" }).format(numeric); } catch { return `${amount} ${currency}`; }
};
const recipientRequirements: Array<{ key: keyof Recipient; label: string }> = [
  { key:"name", label:"ad soyad" }, { key:"email", label:"e-posta" }, { key:"phone", label:"telefon" },
  { key:"address1", label:"açık adres" }, { key:"countryCode", label:"ülke" }, { key:"cityName", label:"şehir" },
  { key:"districtName", label:"ilçe" },
];
const missingRecipientFields = (recipient: ShipmentV1["recipient"]) => recipientRequirements
  .filter(({key})=>!String(recipient?.[key]??"").trim()).map(({label})=>label);
const sourceName = (channel:string) => ({ SHOPIFY:"Shopify", TRENDYOL:"Trendyol", N11:"N11", AMAZON:"Amazon" }[channel.toUpperCase()]||channel);

function Header({ title, back }: { title:string; back?:string }) { return <header className="fulfillment-page-header">{back ? <Link to={back} aria-label="Geri"><ArrowLeft size={18}/></Link> : <span/>}<h1>{title}</h1><span/></header>; }
function Alert({ value }: { value:Notice | null }) { return value ? <div className={`fulfillment-feedback ${value.kind}`} role={value.kind === "error" ? "alert" : "status"}>{value.kind === "error" ? <CircleAlert size={18}/> : <CheckCircle2 size={18}/>}<span>{value.message}{value.code && <small>Hata kodu: {value.code}</small>}</span></div> : null; }

function Queue() {
  const [items,setItems] = useState<QueueItem[]>([]); const [loading,setLoading] = useState(true); const [notice,setNotice] = useState<Notice|null>(null);
  const load = useCallback(async () => { setLoading(true); try { const summaries=(await shipmentApi.list("pending")).filter(x=>x.state==="PREPARING"); setItems(await Promise.all(summaries.map(async x=>{ try{return {...x,detail:await shipmentApi.get(x.id)}}catch{return x}}))); } catch(e){setNotice(fail(e))} finally{setLoading(false)} },[]);
  useEffect(()=>{void load()},[load]);
  const total=items.reduce((sum,x)=>sum+(x.detail?.requiredContents.reduce((n,l)=>n+l.quantityBaseInt,0)||0),0);
  return <div className="fulfillment-page"><Header title="Paketleme"/><section className="fulfillment-hero"><div><span>PAKETLEME KUYRUĞU</span><strong>{items.length}</strong><p>Toplaması tamamlanan sipariş</p></div><PackageCheck/></section>
    <div className="fulfillment-summary"><span>{items.length} sipariş</span><span>{total} adet</span><Link to="/shipments?view=dispatch">Sevke hazırları aç</Link></div><Alert value={notice}/>
    {loading ? <div className="fulfillment-empty"><RefreshCw className="animate-spin"/>Kuyruk yükleniyor…</div> : items.length ? <div className="fulfillment-list">{items.map(item=>{const qty=item.detail?.requiredContents.reduce((n,l)=>n+l.quantityBaseInt,0)||0;return <article className="fulfillment-order-card" key={item.id}><div className="fulfillment-card-top"><span className="platform-pill">{item.sourceChannel}</span><span className="status-pill warning">{statusText[item.state]}</span></div><h2>{item.orderNumber}</h2><p className="customer-name">{item.customerName||"Müşteri bilgisi yok"}</p><dl><div><dt>İçerik</dt><dd>{item.detail?.requiredContents.length||0} ürün · {qty} adet</dd></div><div><dt>Ağırlık</dt><dd>Paketlemede ölçülecek</dd></div></dl><Link className="fulfillment-primary" to={`/shipments?shipmentId=${encodeURIComponent(item.id)}`}>Paketlemeyi Başlat <ChevronRight size={18}/></Link></article>})}</div> : <div className="fulfillment-empty"><CheckCircle2/>Paketleme bekleyen sipariş yok.</div>}
  </div>;
}

function Setup({ shipment,onSaved,busy,setBusy,setNotice }: { shipment:ShipmentV1;onSaved:(s:ShipmentV1)=>void;busy:boolean;setBusy:(b:boolean)=>void;setNotice:(n:Notice|null)=>void }) {
  const make=(all:boolean):Draft=>({template:"",length:"",width:"",height:"",weight:"",contents:Object.fromEntries(shipment.requiredContents.map(x=>[x.productId,all?String(x.quantityBaseInt):"0"]))});
  const [drafts,setDrafts]=useState<Draft[]>(()=>[make(true)]); const op=useRef(key());
  const update=(i:number,k:keyof Draft,v:string)=>setDrafts(xs=>xs.map((x,j)=>j===i?{...x,[k]:v}:x));
  const choose=(i:number,name:string,size?:readonly number[])=>setDrafts(xs=>xs.map((x,j)=>j===i?{...x,template:name,...(size?{length:String(size[0]),width:String(size[1]),height:String(size[2])}:{})}:x));
  const valid=drafts.every(x=>Number(x.length)>0&&Number(x.width)>0&&Number(x.height)>0&&Number(x.weight)>0);
  const save=async()=>{setBusy(true);setNotice(null);try{await shipmentApi.definePackages(shipment.id,drafts.map((x,i)=>({packageNumber:i+1,measured:{lengthMm:Math.round(Number(x.length)*10),widthMm:Math.round(Number(x.width)*10),heightMm:Math.round(Number(x.height)*10),weightGrams:Number(x.weight)},contents:shipment.requiredContents.map(l=>({productId:l.productId,quantityBaseInt:Number(x.contents[l.productId]||0)})).filter(l=>l.quantityBaseInt>0)})),op.current);onSaved(await shipmentApi.get(shipment.id));setNotice({kind:"success",message:"Paket ölçüleri ve içerikleri kesinleştirildi."})}catch(e){setNotice(fail(e))}finally{setBusy(false)}};
  return <><section className="fulfillment-order-summary"><span className="platform-pill">{shipment.sourceChannel}</span><h2>{shipment.orderNumber}</h2><p>{shipment.requiredContents.length} ürün · {shipment.requiredContents.reduce((n,x)=>n+x.quantityBaseInt,0)} adet</p></section>
    <section className="fulfillment-card"><h3>Sipariş içeriği</h3>{shipment.requiredContents.map(x=><div className="content-line" key={x.productId}><span className="content-icon"><Box size={22}/></span><span><strong>{x.title}</strong><small>{x.sku}</small></span><b>{x.quantityBaseInt}×</b></div>)}</section>
    {drafts.map((d,i)=><section className="fulfillment-card package-draft" key={i}><div className="section-heading"><div><span>PAKET {i+1}</span><h3>Koli ve ölçüler</h3></div>{drafts.length>1&&<button onClick={()=>setDrafts(xs=>xs.filter((_,j)=>j!==i))}>Kaldır</button>}</div><div className="box-template-grid">{boxes.map(b=><button aria-pressed={d.template===b.name} className={d.template===b.name?"selected":""} onClick={()=>choose(i,b.name,b.size)} key={b.name}><strong>{b.name}</strong><small>{b.size.join("×")} cm</small></button>)}<button aria-pressed={d.template==="Özel"} className={d.template==="Özel"?"selected":""} onClick={()=>choose(i,"Özel")}><strong>Özel ölçü</strong><small>Manuel girin</small></button></div><div className="dimension-grid"><label>Uzunluk (cm)<input inputMode="decimal" value={d.length} onChange={e=>update(i,"length",e.target.value)}/></label><label>Genişlik (cm)<input inputMode="decimal" value={d.width} onChange={e=>update(i,"width",e.target.value)}/></label><label>Yükseklik (cm)<input inputMode="decimal" value={d.height} onChange={e=>update(i,"height",e.target.value)}/></label></div><label className="weight-field">Ağırlık (gram)<input inputMode="numeric" value={d.weight} onChange={e=>update(i,"weight",e.target.value)} placeholder="Örn. 1850"/></label><details><summary>Bu paketteki ürünleri düzenle</summary>{shipment.requiredContents.map(l=><label className="package-content-input" key={l.productId}>{l.sku}<input inputMode="numeric" value={d.contents[l.productId]||"0"} onChange={e=>setDrafts(xs=>xs.map((x,j)=>j===i?{...x,contents:{...x.contents,[l.productId]:e.target.value}}:x))}/></label>)}</details></section>)}
    <button className="fulfillment-secondary" onClick={()=>setDrafts(xs=>[...xs,make(false)])}><Plus size={18}/> Paket ekle</button><button className="fulfillment-primary" disabled={busy||!valid} onClick={()=>void save()}>Paketleri Kaydet ve Devam Et <ChevronRight size={18}/></button></>;
}

function Offers({ shipment,onSaved,busy,setBusy,setNotice }: { shipment:ShipmentV1;onSaved:(s:ShipmentV1)=>void;busy:boolean;setBusy:(b:boolean)=>void;setNotice:(n:Notice|null)=>void }) {
  const [live,setLive]=useState<GeliverLivePackage[]>([]); const [loaded,setLoaded]=useState(false); const [selected,setSelected]=useState<Record<string,string>>({}); const loadOp=useRef(key()); const buyOps=useRef(new Map<string,string>()); const missing=missingRecipientFields(shipment.recipient);
  const load=async(refresh=false)=>{setBusy(true);setNotice(null);try{const data=refresh?await shipmentApi.refreshGeliver(shipment.id):await shipmentApi.loadGeliverOffers(shipment.id,loadOp.current);setLive(data);setLoaded(true);setNotice({kind:data.some(x=>x.offers.length)?"success":"info",message:data.some(x=>x.offers.length)?"Canlı Geliver teklifleri güncellendi.":"Teklif henüz hazır değil; biraz sonra yenileyin."})}catch(e){setNotice(fail(e))}finally{setBusy(false)}};
  useEffect(()=>{if(shipment.state!=="PREPARING")void load(true)},[]);
  const active=live.find(x=>!x.selectedOffer)||live[0]; const offer=active?.offers.find(x=>x.id===selected[active.packageId]);
  const buy=async()=>{if(!offer||!active)return;setBusy(true);const mapKey=`${shipment.id}:${offer.id}`;if(!buyOps.current.has(mapKey))buyOps.current.set(mapKey,key());try{const updated=await shipmentApi.acceptGeliverOffer(shipment.id,offer.id,buyOps.current.get(mapKey)!);onSaved(updated);setLive(await shipmentApi.refreshGeliver(shipment.id));setSelected({});setNotice({kind:"success",message:updated.state==="LABEL_READY"?"Gönderi, takip numarası ve etiket hazır.":"Paket gönderisi oluşturuldu; sıradaki paketi seçin."})}catch(e){setNotice(fail(e))}finally{setBusy(false)}};
  if(!loaded)return <section className="fulfillment-card"><div className="section-heading"><div><span>GELİVER</span><h3>Canlı kargo teklifleri</h3></div><Truck/></div><div className="package-measure-summary">{shipment.packages.map(p=><p key={p.id}><strong>Paket {p.packageNumber}</strong><span>{p.dimensionsMm.length/10}×{p.dimensionsMm.width/10}×{p.dimensionsMm.height/10} cm · {(p.weightGrams/1000).toLocaleString("tr-TR")} kg</span></p>)}</div><div className="recipient-summary" aria-label="Teslimat alıcısı"><div className="section-heading"><div><span>ALICI</span><h3>{shipment.recipient?.name||"Teslimat bilgisi eksik"}</h3></div></div><dl><div><dt>Telefon</dt><dd>{shipment.recipient?.phone||"—"}</dd></div><div><dt>Şehir / ilçe</dt><dd>{[shipment.recipient?.cityName,shipment.recipient?.districtName].filter(Boolean).join(" / ")||"—"}</dd></div><div><dt>Açık adres</dt><dd>{[shipment.recipient?.address1,shipment.recipient?.address2].filter(Boolean).join(", ")||"—"}</dd></div></dl><p>{sourceName(shipment.sourceChannel)} siparişinden alındı</p></div>{missing.length>0&&<div className="fulfillment-feedback error" role="alert"><CircleAlert size={18}/><span>Sipariş teslimat bilgileri eksik<small>Eksik alanlar: {missing.join(", ")}. Warehouse içinde geçici adres girmeyin; canonical sipariş kaydını düzeltin.</small></span></div>}<button className="fulfillment-primary" disabled={busy||missing.length>0} onClick={()=>void load()}>Geliver Kargo Tekliflerini Getir</button></section>;
  return <section className="fulfillment-card offers-card"><div className="section-heading"><div><span>CANLI FİYATLAR</span><h3>Geliver teklifleri</h3></div><button aria-label="Teklifleri yenile" onClick={()=>void load(true)}><RefreshCw size={18}/></button></div><p className="helper-copy">En ucuz teklif otomatik seçilmez.</p><div className="offer-list">{active?.offers.map(o=><button className={selected[active.packageId]===o.id?"selected":""} onClick={()=>setSelected(x=>({...x,[active.packageId]:o.id}))} key={o.id}><span className="offer-radio">{selected[active.packageId]===o.id&&<Check size={14}/>}</span><span><strong>{o.carrier}</strong><small>{o.service}{o.durationTerms?` · ${o.durationTerms}`:""}</small>{o.estimatedArrivalAt&&<small>Tahmini: {new Date(o.estimatedArrivalAt).toLocaleDateString("tr-TR")}</small>}</span><b>{price(o.amountLocal||o.amount,o.currencyLocal||o.currency)}</b></button>)}</div>{!active?.offers.length&&<div className="fulfillment-empty compact">Teklif bulunamadı.</div>}<button className="fulfillment-primary" disabled={busy||!offer} onClick={()=>void buy()}>{offer?`${offer.carrier} Teklifini Satın Al · ${price(offer.amountLocal||offer.amount,offer.currencyLocal||offer.currency)}`:"Satın almak için teklif seçin"}</button></section>;
}

function Label({ shipment,busy,setBusy,setNotice }: {shipment:ShipmentV1;busy:boolean;setBusy:(b:boolean)=>void;setNotice:(n:Notice|null)=>void}) {
  const [packageId,setPackageId]=useState(shipment.packages.find(x=>x.label)?.id||shipment.packages[0]?.id||""); const [jobs,setJobs]=useState<PrintJob[]>([]); const [modal,setModal]=useState<PrintJob|null>(null); const [reason,setReason]=useState<ReprintReason|"">(""); const [explanation,setExplanation]=useState(""); const ops=useRef(new Map<string,string>()); const pack=shipment.packages.find(x=>x.id===packageId)||shipment.packages[0];
  useEffect(()=>{warehouseAdminApi.listPrintJobs().then(x=>setJobs(x.filter(j=>j.purpose==="SHIPPING"))).catch(()=>undefined)},[]); if(!pack)return null; const job=shippingPrintJobFor(jobs,pack);
  const print=async()=>{setBusy(true);if(!ops.current.has(pack.id))ops.current.set(pack.id,key());try{const created=await shipmentApi.queueNativeLabel(shipment.id,pack.id,ops.current.get(pack.id)!);setJobs(x=>[created,...x.filter(j=>j.id!==created.id)]);setNotice({kind:"success",message:"Sağlayıcı etiketi yazıcı kuyruğuna alındı; fiziksel baskı ayrı izlenir."})}catch(e){setNotice(fail(e))}finally{setBusy(false)}};
  const reprint=async()=>{if(!modal||!reason)return;setBusy(true);try{const created=await warehouseAdminApi.reprint(modal.id,reason,explanation||undefined);setJobs(x=>[created,...x]);setModal(null);setNotice({kind:"success",message:"Yeniden baskı nedeni ile kuyruğa alındı; yeni gönderi satın alınmadı."})}catch(e){setNotice(fail(e))}finally{setBusy(false)}};
  return <><section className="label-safety"><PackageCheck/><span><strong>Bu etiketi doğru pakete yapıştırın</strong><small>{packageName(shipment,pack)}</small></span></section>{shipment.packages.length>1&&<div className="package-tabs">{shipment.packages.map(p=><button className={p.id===pack.id?"selected":""} onClick={()=>setPackageId(p.id)} key={p.id}>Paket {p.packageNumber}</button>)}</div>}<section className="fulfillment-card label-metadata"><div><span>Sipariş</span><strong>{shipment.orderNumber}</strong></div><div><span>Kargo</span><strong>{packageCarrierName(pack)}</strong></div><div><span>Takip no</span><strong>{pack.booking?.trackingNumber||"Hazırlanıyor"}</strong></div><div><span>Ölçü / ağırlık</span><strong>{pack.dimensionsMm.length/10}×{pack.dimensionsMm.width/10}×{pack.dimensionsMm.height/10} cm · {(pack.weightGrams/1000).toLocaleString("tr-TR")} kg</strong></div></section><section className="fulfillment-card label-preview"><div className="section-heading"><div><span>100×150 MM</span><h3>Kargo etiketi</h3></div><span className="status-pill ready">HAZIR</span></div>{pack.label?.reference?<iframe title="Kargo etiketi önizleme" src={pack.label.responsiveReference||pack.label.reference}/>:<div className="fulfillment-empty compact">Etiket sağlayıcıdan bekleniyor.</div>}<p className={`printer-status ${job?"":"pending"}`}>{job?<CheckCircle2 size={16}/>:<CircleAlert size={16}/>} {job?`Yazıcı işi: ${job.status}`:"Henüz yazıcı kuyruğuna alınmadı"}</p><button className="fulfillment-primary" disabled={busy||!pack.label} onClick={()=>void print()}><Printer size={18}/>Etiketi Yazdır</button>{job&&<button className="fulfillment-secondary" onClick={()=>setModal(job)}><RotateCcw size={17}/>Neden belirterek yeniden yazdır</button>}</section><Link className="fulfillment-primary dark" to="/shipments?view=dispatch">Sevke Hazır Paketlere Git <ChevronRight size={18}/></Link>{modal&&<div className="fulfillment-modal-layer"><section className="fulfillment-modal" role="dialog" aria-modal="true" aria-labelledby="reprint-title"><button className="modal-close" aria-label="Kapat" onClick={()=>setModal(null)}><X/></button><h2 id="reprint-title">Yeniden baskı nedeni</h2><p>Orijinal provider etiketi kullanılır.</p><select value={reason} onChange={e=>setReason(e.target.value as ReprintReason|"")}><option value="">Neden seçin</option><option value="DAMAGED_OUTPUT">Hasarlı çıktı</option><option value="LOST">Kayıp</option><option value="PRINTER_ERROR">Yazıcı hatası</option><option value="OTHER">Diğer</option></select>{reason==="OTHER"&&<textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Açıklama"/>}<button className="fulfillment-primary" disabled={!reason||(reason==="OTHER"&&!explanation.trim())} onClick={()=>void reprint()}>Yeniden Yazdır</button></section></div>}</>;
}

function CancelAction({ shipment, onSaved, busy, setBusy, setNotice }: { shipment:ShipmentV1;onSaved:(s:ShipmentV1)=>void;busy:boolean;setBusy:(b:boolean)=>void;setNotice:(n:Notice|null)=>void }) {
  const [reason,setReason]=useState("");
  if (["HANDED_OFF","DISPATCHED","CANCELLED"].includes(shipment.state)) return null;
  const cancel=async()=>{setBusy(true);try{onSaved(await shipmentApi.cancel(shipment.id,reason.trim()));setNotice({kind:"success",message:"Sevkiyat fiziksel teslimden önce iptal edildi."})}catch(e){setNotice(fail(e))}finally{setBusy(false)}};
  return <details className="fulfillment-card"><summary className="helper-copy">Teslim öncesi iptal</summary><label className="weight-field">İptal nedeni<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="fulfillment-secondary" disabled={busy||!reason.trim()} onClick={()=>void cancel()}>{preservedActionLabels[0]}</button></details>;
}

function Flow({ id }:{id:string}) { const {user}=useAuth();const [shipment,setShipment]=useState<ShipmentV1|null>(null);const [busy,setBusy]=useState(true);const [notice,setNotice]=useState<Notice|null>(null);useEffect(()=>{shipmentApi.get(id).then(setShipment).catch(e=>setNotice(fail(e))).finally(()=>setBusy(false))},[id]);const allowed=hasWarehousePermission(user,"shipping:manage");return <div className="fulfillment-page"><Header title={shipment?.state==="LABEL_READY"?"Kargo Etiketi":shipment?.packageCount?"Geliver Teklifleri":"Paket Hazırlama"} back="/shipments"/><Alert value={notice}/>{busy&&!shipment&&<div className="fulfillment-empty"><RefreshCw className="animate-spin"/>Sipariş yükleniyor…</div>}{shipment&&!allowed&&<div className="fulfillment-empty"><CircleAlert/>shipping:manage yetkisi gerekli.</div>}{shipment&&allowed&&shipment.state==="PREPARING"&&shipment.packageCount===0&&<Setup shipment={shipment} onSaved={setShipment} busy={busy} setBusy={setBusy} setNotice={setNotice}/>} {shipment&&allowed&&shipment.state!=="LABEL_READY"&&shipment.packageCount>0&&<Offers shipment={shipment} onSaved={setShipment} busy={busy} setBusy={setBusy} setNotice={setNotice}/>} {shipment&&allowed&&shipment.state==="LABEL_READY"&&<Label shipment={shipment} busy={busy} setBusy={setBusy} setNotice={setNotice}/>} {shipment&&allowed&&<CancelAction shipment={shipment} onSaved={setShipment} busy={busy} setBusy={setBusy} setNotice={setNotice}/>}{shipment&&["HANDED_OFF","DISPATCHED"].includes(shipment.state)&&<div className="dispatch-success"><CheckCircle2/><h2>Sevk edildi</h2><p>{shipment.orderNumber}</p></div>}</div> }

function Ready() {
  const {user}=useAuth();const [items,setItems]=useState<QueueItem[]>([]);const [selected,setSelected]=useState<string[]>([]);const [notice,setNotice]=useState<Notice|null>(null);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [evidence,setEvidence]=useState("");const [result,setResult]=useState<BulkHandoffResult|null>(null);const op=useRef(key());const canDispatch=hasWarehousePermission(user,"shipping:dispatch");
  useEffect(()=>{shipmentApi.list("pending").then(xs=>Promise.all(xs.filter(x=>x.state==="LABEL_READY").map(async x=>({...x,detail:await shipmentApi.get(x.id)})))).then(setItems).catch(e=>setNotice(fail(e))).finally(()=>setLoading(false))},[]);
  const send=async()=>{setLoading(true);try{const r=await shipmentApi.bulkHandoff(selected,evidence,op.current);setResult(r);setOpen(false);setItems(xs=>xs.filter(x=>!r.data.some(y=>y.shipmentId===x.id&&y.success)));setSelected([])}catch(e){setNotice(fail(e))}finally{setLoading(false)}};
  if(result)return <div className="fulfillment-page"><Header title="Sevkiyat" back="/shipments"/><section className="dispatch-success"><CheckCircle2/><span>TOPLU SEVK TAMAMLANDI</span><h2>{result.summary.dispatched} gönderi sevk edildi</h2><p>{result.summary.failed?`${result.summary.failed} kayıt başarısız; bu kayıtların stok hareketi yapılmadı.`:"Fiziksel taşıyıcı teslimi doğrulandı."}</p><dl><div><dt>İşlem no</dt><dd>{result.batchOperationId.slice(0,13)}</dd></div><div><dt>Zaman</dt><dd>{new Date().toLocaleString("tr-TR")}</dd></div><div><dt>Operatör</dt><dd>{user?.username||"Operatör"}</dd></div></dl></section><button className="fulfillment-primary" onClick={()=>setResult(null)}>Listeye Dön</button></div>;
  return <div className="fulfillment-page"><Header title="Sevke Hazır" back="/shipments"/><section className="fulfillment-hero ready"><div><span>SEVKE HAZIR</span><strong>{items.length}</strong><p>Fiziksel taşıyıcı teslimi bekliyor</p></div><Truck/></section><Alert value={notice}/>{items.length>0&&<label className="select-all"><input type="checkbox" checked={selected.length===items.length} onChange={e=>setSelected(e.target.checked?items.map(x=>x.id):[])}/> Tümünü seç <span>{selected.length} seçili</span></label>}{loading&&!items.length?<div className="fulfillment-empty"><RefreshCw className="animate-spin"/>Liste yükleniyor…</div>:<div className="fulfillment-list">{items.map(item=><article className={`ready-card ${selected.includes(item.id)?"selected":""}`} key={item.id}><label><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(xs=>e.target.checked?[...xs,item.id]:xs.filter(x=>x!==item.id))}/><span><strong>{item.orderNumber}</strong><small>{item.sourceChannel} · {item.customerName||"Müşteri"}</small></span><span className="status-pill ready">SEVKE HAZIR</span></label>{item.detail?.packages.map(p=><div className="ready-package" key={p.id}><span>{packageName(item.detail!,p)}</span><strong>{packageCarrierName(p)}</strong><small>{p.booking?.trackingNumber||"Takip no bekleniyor"}</small><Link to={`/shipments?shipmentId=${item.id}`}>Etiketi aç</Link></div>)}</article>)}</div>}{canDispatch&&<button className="fulfillment-primary sticky-action" disabled={!selected.length} onClick={()=>{op.current=key();setOpen(true)}}>{selected.length?`${selected.length} Gönderiyi Toplu Sevk Et`:"Sevk için paket seçin"}</button>}{open&&<div className="fulfillment-modal-layer"><section className="fulfillment-modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><button className="modal-close" aria-label="Kapat" onClick={()=>setOpen(false)}><X/></button><div className="modal-truck"><Truck/></div><h2 id="confirm-title">{selected.length} gönderiyi kargoya teslim ettiniz mi?</h2><p>Bu onay stok ve FIFO/COGS hareketini başlatır; geri alınamaz.</p><label>Teslim kanıtı / tutanak referansı<input value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Örn. dock-7 / tutanak-184"/></label><div className="modal-actions"><button className="fulfillment-secondary" onClick={()=>setOpen(false)}>Vazgeç</button><button className="fulfillment-primary" disabled={!evidence.trim()} onClick={()=>void send()}>{preservedActionLabels[1]}</button></div></section></div>}</div>;
}

export default function ShipmentPage(){const [params]=useSearchParams();const id=params.get("shipmentId");if(id)return <Flow id={id}/>;if(params.get("view")==="dispatch")return <Ready/>;return <Queue/>}
